services:
  postgres:
    image: postgres:16-alpine
    container_name: therun-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - therun_db:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      therun_net:
        ipv4_address: 172.16.0.30

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: therun-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      # Dans le réseau docker, l’hôte DB est "postgres"
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      NODE_ENV: development
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npx prisma generate && npm run start:dev"
    networks:
      therun_net:
        ipv4_address: 172.16.0.40

volumes:
  therun_db:

networks:
  therun_net:
    name: therun_net
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/16